name: CaptchaPlugin
version: '${project.version}'
main: captchaplugin.captchaplugin.CaptchaPlugin
api-version: 1.16
commands:
  validate:
    description: Start validation for another player
    usage: /<command> NICK
  validateAnswer:
    description: Validate answer from player
    usage: /<command> OPTION